### ISSUE TITLE
Feature: Add support for optimizeFor isoline parameters

### ISSUE THREAD

**Issue by hrecht** [munterfinger/hereR#119]
**Description**
It would be very helpful if the isoline function supported all of the [API parameters](https://developer.here.com/documentation/isoline-routing-api/8.4.0/api-reference-swagger.html), including `optimizeFor`. 

Or if that can already be used, how do we include it? Thanks for this great package!

**Comment by munterfinger** [comment]
Hi thanks for reporting and the positive feedback on the package.

Can you test with `remotes::install_github("munterfinger/hereR@feature/isoline-optimize")`?
