### ISSUE TITLE
Feature: Remove limits in case of paid plan

### ISSUE THREAD

**Issue by munterfinger** [munterfinger/hereR#137]
Inspired by https://github.com/mobilityinstitute/hereR/commit/867f1d7d6cd6ce73fddbaf590ab2585776b58acb:

- New environment variable `HERE_FREEMIUM` and `hereR::set_freemium(FALSE)`
- Deactivate rate limits in request in paid plans, deprecate `hereR::set_rate_limits(FALSE)`
- Remove limits of matrix size in `route_matrix` in paid plans using `.get_freemium()`
- Remove further restricitons?

**Comment by szaboildi** [comment]
The matrix size should probably still be limited, even in case of the Pro plan. The limit for that plan is 10000x10000 (https://developer.here.com/pricing#plan-details).
