### ISSUE TITLE
Geocode error

### ISSUE THREAD

**Issue by fdfranke** [munterfinger/hereR#74]
Hi,
I've got the following error with the exemple:
geocode(c("Schweighofstrasse 190, Zurich, Switzerland", "Hardstrasse 48, Zurich, Switzerland"))
NULL
Warning messages:
1: In (function (res)  : Request 'id = 2' failed: Status 400. 
2: In (function (res)  : Request 'id = 1' failed: Status 400. 
> 

Status 400 means Bad Request.

Any ideas?

**Comment by munterfinger** [comment]
Hi, thanks for reporting.

This seems to be the same issue as #73, which should be fixed now. Release of hereR v0.5.1 is submitted to CRAN.

Could you try again with the dev version from GitHub? 
`remotes::install_github("munterfinger/hereR")`

**Comment by fdfranke** [comment]
Great, the dev version worked fine. No more warnings!

Thank you!
